[package]
name = "ptgui"
version = "0.1.1"
authors = ["STBoyden <stboyden@stboyden.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = {git = "https://github.com/deltaphc/raylib-rs", branch = "three"}
